Add DualSimTracer doc
SpinalHDL/SpinalDoc-RTD pull request #222
Opened 2023-10-18 14:15 UTC by Dolu1990

Actualy used in NaxRiscv for day long sim

2023-10-20 11:28 UTC, andreasWallner requested changes
❤️ the idea!

2023-10-20 11:28 UTC, andreasWallner commented on source/SpinalHDL/Simulation/bootstraps.rst
> +Either you can run a dual lock-step simulation, with one running a bit delayed from the the other one, and which will start recording the wave once the other simulation had a failure.
```suggestion
Or you can run a dual lock-step simulation, with one running a bit delayed from the the other one, and which will start recording the wave once the leading simulation had a failure.
```

2023-10-20 11:28 UTC, andreasWallner commented on source/SpinalHDL/Simulation/bootstraps.rst
> +To do this, you can use the DualSimTracer utility, which will ask you the compiled hardware, the window of time you want to capture the wave before falure, and a seed.
```suggestion
To do this, you can use the DualSimTracer utility, with parameters for the compiled hardware, the window of time you want to capture before failure, and a seed.
```

2023-10-20 13:14 UTC, Dolu1990 commented
Thanks for the review :)

2023-10-20 13:14 UTC, merged

2026-04-27 19:20 UTC, mrcmry commented
Deleted merged branch for cleanup.