regif documented
SpinalHDL/SpinalDoc-RTD pull request #73
Opened 2022-01-26 16:16 UTC by jijingg

here to pay my debts 😆，register interface build tools document done!

2022-01-26 18:29 UTC, wifasoi requested changes
I rewritten some part.
You can add my correction, or just ignore them.

Anyway, thanks for the docs;
Now your doc tax is payed and you can sleep peacefully... FOR NOW! *\***evil laughter***\*

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +Easy Way creat interruption:
```suggestion
this is a very tedious and repetitive work, a better way is to use the "factory" paradigm to auto-generate the documentation for each signal.

now th InterruptFactory can do that.
    
Easy Way creat interruption:
```

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +- Auto Document generate
```suggestion
- Automatic address, fields allocation and conflict detection
- 28 Register Access types(Covering the 25 types defined by the UVM standard)
- Automatic documentation generation
```

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +Automatic address allocate
```suggestion
Automatic address allocation
```

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +Automatic fileds allocate
```suggestion
Automatic fileds allocation
```

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +Most of these come from UVM
```suggestion
Most of these come from UVM specification
```

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +----------------------
```suggestion
Automatic documentation generation
----------------------------------
```

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +You Extend document Type based on Trait BusIfVistor
```suggestion
You can add your document Type by extending the `BusIfVistor` Trait 
```

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +--------------
```suggestion
28 Access Types
---------------
```

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +------------------
```suggestion
Automatic allocation
--------------------
```

2022-01-26 18:29 UTC, wifasoi commented on source/SpinalHDL/Libraries/regIf.rst
> +============
```suggestion
RegIf
=====
```

2022-01-26 18:30 UTC, wifasoi commented
Don't worry about the cicd.. for now.
I didn't have the time to fix the dam thing yet :D

2022-01-27 02:56 UTC, jijingg commented
> I rewritten some part.

thank you very much for your careful revision, ❤️ 

> you can sleep peacefully... FOR NOW

 haha..  you'r right

2022-01-27 03:07 UTC, jijingg commented
> You can add my correction

done ,  thanks

2022-01-27 17:46 UTC, merged